### ISSUE TITLE
Parser should include a way to include and parse other views

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#1966]
The user guide even gives an example of using a plugin `{+ include something.php +}`, but we don't have a way to do this. Since we're in the parser, it should run the included view in the parser always.

**Comment by adnzaki** [comment]
Hi Lonnie, I have implemented that way using my custom plugin and it works very well. Here is the code:
```
        public static function include(array $params = [])
	{
		$parser = \Config\Services::parser();
		return $parser->render(...$params);
	}
```
And in app/Config/View.php, I added a line to this code:
```
        public $plugins = [
		'include' => '\Actudent\Core\Config\ActudentParserPlugin::include',
	];
```
In view parser, simply write `{+ include filename +}` or if it is in nested view folder: `{+ include folderName\filename +}`. 
Note: 
- I'm using code modularization in my project, `Actudent` is the root of the module.
- The plugin has not support filename with symbol.

**Comment by jim-parry** [comment]
The above code shows how to load a plugin from who-know-where, which does who-knows-what, and possibly only with a filename without extension.
It sounds lke you have partially addressed the issue in your custom code, but it isn't clear that you have a solution for the original question.
Clarification would be appreciated.
