### ISSUE TITLE
Bug: appstarter HealthTest::testBaseUrlHasBeenSet fails

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#3977]
**Describe the bug**
HealthTest::testBaseUrlHasBeenSet fails.

**CodeIgniter 4 version**
4.0.4

**Affected module(s)**
tests

**Expected behavior, and steps to reproduce if appropriate**
~~All tests should pass.~~
HealthTest is supposed to check for various "common mistakes" in a user's app, including if App::$baseURL is set.
So fails only when a user does not set baseURL.

```
$ composer create-project codeigniter4/appstarter ci4
$ cd ci4/
$ composer test
...
There was 1 failure:

1) HealthTest::testBaseUrlHasBeenSet
Failed asserting that false is true.

/Users/kenji/tmp/ci4/tests/unit/HealthTest.php:31

FAILURES!
Tests: 5, Assertions: 6, Failures: 1.
Script phpunit handling the test event returned with error code 1
```

**Context**
 - OS: [macOS 10.15.7]
 - Web server [n/a]
 - PHP version [7.4.13]

**Comment by kenjis** [comment]
https://github.com/codeigniter4/CodeIgniter4/blob/3b4e476453f4cf602c417861fab0307fa6420aa0/admin/starter/tests/unit/HealthTest.php#L24
Why `/^app\.baseURL = './` ?

**Comment by kenjis** [comment]
#3865 fixed checking the actual config file, but it seems checking in .env is still wrong. See above.

**Comment by paulbalandan** [comment]
@kenjis I assume your `.env` has the `app.baseURL` populated yet the test fails. If you change the pattern and remove the single quote mark, will it pass? `$env = (bool) preg_grep('/^app\.baseURL = ./', file(HOMEPATH . '.env'));`

**Comment by kenjis** [comment]
@paulbalandan 
If I have the following `.env`, it fails.
```
app.baseURL = http://localhost:8080/
```

If I have the following `.env`, it passes.
```
app.baseURL = 'http://localhost:8080/'
```

I have an another question. If I don't have `.env` file, should the test  fail?

**Comment by paulbalandan** [comment]
Looking at the test code, the `$env` variable will remain `false` because the `is_file` check will fail. So it is mandatory to have the `.env` file.

**Comment by kenjis** [comment]
But after that, the config file is checked.
https://github.com/codeigniter4/CodeIgniter4/blob/3b4e476453f4cf602c417861fab0307fa6420aa0/admin/starter/tests/unit/HealthTest.php#L29

And the assertion is `$this->assertTrue($env || $config);`

`$config` will be `true`, because the config file has `baseURL`.
So even if I don't have `.env`, the test will pass.

It seems checking in `.env` is useless, because `$config` is true.
And the test is almost useless, because it won't fail when I set the `baseURL` in the config file to empty and I don't set `baseURL` in `.env` (or I don't have `.env`).

**Comment by MGatner** [comment]
Requiring the single quote was my mistake, at the time I thought strings needed to be enclosed.

> it won't fail when I set the baseURL in the config file to empty and I don't set baseURL in .env (or I don't have .env)

If you don't have a value for `baseURL` in either `.env` or **app/Config/App.php** it will fail, which is the whole point of the test. That said, I'm not sure that the "Health Tests" idea ever really panned out, we might be better just pulling the whole thing. Since it is specific to the AppStarter we can change it at any time.

**Comment by kenjis** [comment]
@MGatner Sorry, I made a mistake in writing. I fixed my comment.

> If you don't have a value for baseURL in either .env or app/Config/App.php it will fail, which is the whole point of the test. 

If it is the intention of the test, should the assert be like this? Is my understanding of what you say wrong?

```php
$this->assertTrue($env && $config);
```

> That said, I'm not sure that the "Health Tests" idea ever really panned out, we might be better just pulling the whole thing. 

I will send a PR.

**Comment by kenjis** [comment]
How about this? #4239

**Comment by MGatner** [comment]
No, that is still missing the point. Let me try to break this down more:

`App::$baseURL` must have a value set or the application won't work. `HealthTest` was supposed to check for various "common mistakes" in a user's app, including if `App::$baseURL` is set. Because we set the environment variable `app.baseURL` in PHPUnit.xml (so the app will work) we cannot just test `config('App')->baseURL` because that will always have a valid value. So we check the two other sources:

1. **.env**: This check is pretty straightforward except for the single quote issue. We parse the file for a non-empty `app.baseURL` value
2. **app/Config/App.php**: Because we cannot instantiate this class without it loading from the environment (meme times above) we use the bundled  `ConfigReader` to check the actual value in that file itself. 

If either 1 or 2 has a non-empty value, then the configuration will be valid. Hence the `||`, *not* `&&`.

**Comment by kenjis** [comment]
The default `app/Config/App.php` has a valid URL, so 2. is true. Then, the assertion is true by default.


> Because we set the environment variable app.baseURL in PHPUnit.xml

Thank you. I hadn't noticed it.

**Comment by MGatner** [comment]
Yes by default the HealthTest should pass on a new AppStarter instance. It fails if someone clears that Config value or uncomments the line in .env without adding a URL
