### ISSUE TITLE
Bug: Debug Toolbar - Memory Leak - Allocation Exception

### ISSUE THREAD

**Issue by najdanovicivan** [codeigniter4/CodeIgniter4#4137]
**Describe the bug**
In CodeIgniter\Debug\Toolbar  run() method we have the following code to print variables
```
$varData[esc($key)] = is_string($value) ? esc($value) : '<pre>' . esc(print_r($value, true)) . '</pre>';
```
The issue here is that print_r() on object may lead to very high memory usage when $value is object or an array of objects

**CodeIgniter 4 version**
github-develop 

**Affected module(s)**
Debug\Toolbar

**Expected behavior, and steps to reproduce if appropriate**

I don't know if this is a good practice but in some of my controllers I'm passing the controller to the view by reference

```
$data['controller'] = &this;
```

I also usually pass array of entity object as $data['items']

In most cases this will work. But if there are a lot of public properties inside the controller or the entity. print_r() will try printing out everything and completely fill the available memory. In the worst possible example when there is for example entity object which have a reference pointer to child entity object and the child entity object has a reference pointer to parent object it will lead to infinitive loop. 

I propose doing a check on $value if it is an object. In case of array check if array items are objects. So this will be a recursive method processing the array. If $value is an object we can then check if method toArray() exist and render the value returned from toArray method otherwise we just return string `object (className)`

**Comment by paulbalandan** [comment]
I am not well-versed in memory leaks issue but is changing to `var_export` not feasible? Also, in terms of infinite looping, I think I saw an example in a dumping function (cannot remember if it is `print_r` or `var_export` or other else) that if the loop exists, it will just print `RECURSION` on that looping part.

**Comment by najdanovicivan** [comment]
var_export might be a solution as it ignores the recursion. I'll check it out to see if how it will perform

**Comment by najdanovicivan** [comment]
It won't be possible to use var_export as it throws an ErrorException with message `var_export does not handle circular references`

**Comment by kenjis** [comment]
How about this?
https://github.com/pradosoft/prado/blob/master/framework/Util/TVarDumper.php

**Comment by najdanovicivan** [comment]
I’ve looked at TVarDumper but I don like adding additional dependency as it bit tricky to manage them.

CI4 needs to be able to run without composer so it will need scripts for copying those in framework

**Comment by najdanovicivan** [comment]
Doctrine debug might be used as an idea how to do it in framework implementation

**Comment by najdanovicivan** [comment]
Also licensing have to be checked doctrine is MIT so it should be compatible. But I’m not sure about prado BSD license

**Comment by WinterSilence** [comment]
You can use updated class  [KO7_Debug](https://github.com/koseven/koseven/blob/devel/system/classes/KO7/Debug.php) or [Fuel\Core\Debug](https://github.com/fuel/core/blob/1.9/develop/classes/debug.php)

**Comment by najdanovicivan** [comment]
@paulbalandan, @MGatner @michalsn  

Do you have some ideas how to properly handle this one ?

**Comment by WinterSilence** [comment]
> I don't know if this is a good practice but in some of my controllers I'm passing the controller to the view by reference
>
> $data['controller'] = &this;

@najdanovicivan see https://www.php.net/manual/en/language.oop5.references.php

~~~php
$data['controller'] = $this;
$data['controller']->x = 5;
echo $this->x; // echo 5
~~~

**Comment by michalsn** [comment]
> I propose doing a check on $value if it is an object. In case of array check if array items are objects. So this will be a recursive method processing the array. If $value is an object we can then check if method toArray() exist and render the value returned from toArray method otherwise we just return string object (className)

I don't have a huge experience in this field, but I like the idea - except for converting objects to arrays. I think we should be able to prevent recursion by storing object hash (https://www.php.net/manual/en/function.spl-object-hash.php). This should be enough for a starter.

We can also measure the current memory consumption - to not exceed it - with functions like `ini_get('memory_limit')` and `memory_get_usage(true)`. But I'm not sure if that will be needed.

**Comment by paulbalandan** [comment]
Fixed by #4590

**Comment by axelf** [comment]
The issue still exists. Using the debug toolbar in development mode the pages chrases with an memory error (Allowed memory size of xxxxx bytes exhausted (tried to allocate xxx bytes))

**Comment by kenjis** [comment]
There is a limit in your memory, so if you have bigger data for the debug toolbar than your memory, 
the error will occur. It is not a bug. Please increase the memory.

If you can reduce memory usage of the debug toolbar, sending a PR is very welcome.
If you find memory leak, open an issue or send a PR, please.
